/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "pitch-black": "#000000",
        "light-linen": "#ffffff",
        "marketplace-gray": "#f4f4f0",
        "graphite-border": "#242423",
        "subtle-ash": "#d1d5dc",
        "creator-pink": "#ff90e8",
        "sunshine-yellow": "#ffc900",
        "surface-dim": "#dcd9d7",
        "surface-bright": "#fcf9f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f1",
        "surface-container": "#f0edeb",
        "surface-container-high": "#eae8e6",
        "surface-container-highest": "#e5e2e0",
        "on-surface": "#1b1c1b",
        "on-surface-variant": "#4c4546",
        "inverse-surface": "#30302f",
        "inverse-on-surface": "#f3f0ee",
        "outline": "#7e7576",
        "outline-variant": "#cfc4c5",
        "surface-tint": "#5e5e5e",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "inverse-primary": "#c6c6c6",
        "secondary": "#5d5f5c",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2e3df",
        "on-secondary-container": "#636562",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#390034",
        "on-tertiary-container": "#c45eb2",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#fcf9f7",
        "on-background": "#1b1c1b",
        "surface": "#fcf9f7",
        "surface-variant": "#e5e2e0",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed": "#e2e3df",
        "secondary-fixed-dim": "#c6c7c3",
        "on-secondary-fixed": "#1a1c1a",
        "on-secondary-fixed-variant": "#454745",
        "tertiary-fixed": "#ffd7f1",
        "tertiary-fixed-dim": "#ffacea",
        "on-tertiary-fixed": "#390034",
        "on-tertiary-fixed-variant": "#7b1c70",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "max-width": "1200px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-xl": "64px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display": ["72px", { lineHeight: "1.1", letterSpacing: "-1.44px", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "1.2", letterSpacing: "-0.396px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", letterSpacing: "-0.2px", fontWeight: "700" }],
        "subheading": ["20px", { lineHeight: "1.4", letterSpacing: "-0.34px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.4", letterSpacing: "-0.32px", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      maxWidth: {
        "site": "1200px",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "float-delayed": "float 6s ease-in-out infinite -3s",
        "fade-up": "fadeUp 0.5s ease forwards",
      },
    },
  },
  plugins: [],
}

